### ISSUE TITLE
design-token-panel-bootstrap.test.ts flaked again under parallel load on zdtp 0.4.10 (#3344 fix may be incomplete)

### ISSUE THREAD

**Issue by Takazudo** [zudolab/zudo-doc#3439]
Observed during epic #3429 wave 2 (#3431), in a package that sub-issue does not touch.

## What happened

A child agent running the full `pnpm --filter @takazudo/zudo-doc test` suite (2208 tests) saw `packages/zudo-doc/src/__tests__/design-token-panel-bootstrap.test.ts` fail once on the first run under CPU contention. It passed in isolation and on a clean full-suite re-run. Final state was green (2208/2208).

## Why this is not just noise

#3344 tracked **this exact test flaking under parallel load** and was closed on 2026-08-10 by bumping `@takazudo/zdtp` 0.4.9 → 0.4.10 (PR #3355), adopting upstream fix `Takazudo/zudo-design-token-panel#568` — deferred continuations now capture the owning document before `await` and cancel quietly if it is gone or swapped.

**This repo is currently on the fixed version:** root pin `0.4.10`, `packages/zudo-doc` peer floor `^0.4.10`, installed `0.4.10`. Verified just now.

So the symptom that fix was meant to eliminate has recurred on the fixed version.

Notably, #3355's own session report carried this caveat:

> One green parallel run is weak evidence for a flake fix — #3344 itself recorded a clean second run on 0.4.9. The fix evidence is upstream's deterministic `document-teardown-race.test.ts` (15 tests; 6-9 fail on 0.4.9, all pass on 0.4.10). The local run shows no regression, nothing stronger.

That caveat now looks load-bearing.

## Important gap in this report

**The error signature was not captured.** The child reported the failure but not the message, so I cannot confirm it was the same `document.getElementById is not a function` unhandled rejection from the bundled zdtp that #3344 described. It may be the same race surviving 0.4.10, a second distinct race, or an unrelated contention failure that happens to hit the same file.

**First action for whoever picks this up: capture the actual error.** Without it, this is a recurrence of a *symptom*, not confirmed recurrence of a *cause*.

## Suggested next steps

1. Reproduce under deliberate parallel load and capture the full failure output (message + stack + whether it is an unhandled rejection).
2. If the signature matches #3344, reopen the upstream conversation — 0.4.10's fix would be incomplete rather than wrong, and upstream's `document-teardown-race.test.ts` presumably does not cover the surviving path.
3. If it differs, this is a new issue and #3344 stays legitimately closed.
4. Consider whether this test warrants `@flaky` quarantine with a tracking-issue link per `TESTING.md` while the cause is open — noting that quarantining hides exactly the signal needed for step 1, so probably not until the signature is captured.

Not blocking epic #3429, whose final state was green.

**Comment by Takazudo** [comment]
Superseded by epic #3452. Planned diagnosis-first per this issue's own "capture the actual error" note: the signature is captured within a fixed budget before any remedy is chosen.
