### ISSUE TITLE
[DTP Bootstrap Flake][Sub] Reproduce within a fixed budget, capture the failure signature, choose the direction

### ISSUE THREAD

**Issue by Takazudo** [zudolab/zudo-doc#3453]
- https://github.com/zudolab/zudo-doc/issues/3452

---

**Wave:** 1
**Execution mode:** subagents — runs alone; no sibling to coordinate with.
**Model:** fable — this is a decision sub-task. It consumes the reproduction and picks which of four downstream directions Wave 2 takes, then rewrites that sub-issue's body. A wrong call either files an upstream bug for a local deadline problem, or patches a test that is correctly sampling a real product bug.

Source issue: #3439

## Your job is diagnosis, not repair

Per `/test-wisdom` Rule 1: *"'Flaky' is not a diagnosis. It is an admission you have not diagnosed it yet."* #3439's own "important gap" is that the failure signature was never captured — the child agent reported the failure but not the message. Everything downstream depends on closing that gap.

**Write no production code in this sub.**

## Fixed budget — do not exceed

- At most **20 full runs** of `pnpm --filter @takazudo/zudo-doc test` under deliberate CPU contention, **or 45 minutes** of reproduction attempts, whichever comes first.
- Record the run count and the observed failure rate, whatever the outcome.

This bound exists so the sub cannot become an open-ended hunt. A negative result within budget is a legitimate, reportable outcome — see (d).

## What to capture

For any failure in `packages/zudo-doc/src/__tests__/design-token-panel-bootstrap.test.ts`:

- the full message and stack
- whether it is an unhandled rejection
- which test within the file failed

Then apply Rule 1's proof obligation: **diff the product's input on a failing run against a passing run.** Identical inputs with only timing differing means a real flake. Differing inputs means a product bug — stop and say so, because quarantine would then be actively harmful.

## Check this hypothesis first — it is cheap and it changes everything

- `packages/zudo-doc/vitest.config.ts` sets **no `testTimeout`** → tests run on vitest's 5000 ms default.
- The file makes **39 bare `vi.waitFor()` calls** with no explicit timeout.
- Installed vitest **4.1.0** documents `waitFor` defaults as `timeout` **1000 ms**, `interval` 50 ms (`dist/index.d.ts`).

That is the "two independent deadlines" root cause from `/test-wisdom`: under load the tighter 1000 ms `waitFor` deadline fires before the test's own 5000 ms budget, and the failure looks like a flake while having nothing to do with #3344's zdtp teardown race. If the captured signature is a `waitFor` timeout rather than `document.getElementById is not a function`, this is outcome (c) and no upstream report is warranted.

## Do NOT quarantine

Quarantine suspends the very coverage that produces the signal this sub needs. `/test-wisdom` permits it only after the nondeterminism is proven to be in the test rather than the product, with a linked issue and a deadline. None of that is established yet.

## Deliverable

Post a findings comment on this epic recording: run count, failure rate, the captured signature (or its absence), the failing-vs-passing input diff, and which outcome holds:

- **(a)** signature matches #3344 (`document.getElementById is not a function` unhandled rejection) → zdtp 0.4.10's fix is incomplete → upstream report to `Takazudo/zudo-design-token-panel`
- **(b)** a different signature → a new local cause, and #3344 stays legitimately closed
- **(c)** a `vi.waitFor` deadline expiry → test-side deadline bug, fixed locally
- **(d) not reproduced within the budget** → do **not** invent a fix. Record the negative result and the budget spent, retitle the Wave 2 sub to "add deadline headroom + failure-diagnostics capture" so a future occurrence is diagnosable, and state plainly that the cause remains open.

Then **edit the Wave 2 sub-issue's body** (`gh issue edit`) with the concrete spec for the selected outcome.

## Acceptance criteria

- Run count and failure rate recorded.
- Signature captured, or (d) declared with the budget spent.
- Failing-vs-passing input diff performed and its verdict stated (test flake vs product bug).
- One of (a)/(b)/(c)/(d) selected, with reasoning.
- Wave 2's body rewritten with the concrete spec.
- No production code changed, no quarantine applied.

## Machine load

This runs the full 2208-test suite repeatedly. It is alone in its wave, and sweep epics run sequentially, so it never contends with a sibling agent.

**Base branch:** `base/sweep-260818-dtp-bootstrap-flake` — PR targets this branch (which itself targets `base/sweep-260818`).

**Comment by Takazudo** [comment]
## Corroborating evidence found during epic #3445 — read before starting

A child agent working on an unrelated topic hit **13 failures in `packages/zudo-doc/src/eject-logo/__tests__/`** during a full `pnpm --filter @takazudo/zudo-doc test` run, and verified via `git stash` that they predate its changes. The manager session then reproduced and diagnosed it — raised as #3465.

**Why this matters for your diagnosis, materially:**

- Those eject-logo failures **do not reproduce in isolation** (7/7 and 40/40 pass scoped). They are load-dependent, exactly like the symptom in #3439.
- `cli-smoke.test.ts` spawns a real subprocess via `spawnSync(process.execPath, …)` with **no `timeout:` option**, so its effective deadline is vitest's default per-test timeout — and `packages/zudo-doc/vitest.config.ts` sets **no `testTimeout`** (vitest 4.1.0 default: 5000 ms).
- **eject-logo has nothing to do with `@takazudo/zdtp`.**

That last point is the load-bearing one. #3439's leading hypothesis was that #3344's zdtp teardown-race fix (0.4.10) is incomplete. But a *second, zdtp-unrelated* suite in the same package failing only under parallel load points at a **package-level deadline budget problem**, not a component-specific race.

**Practical effect on your four outcomes:** this shifts prior weight toward **(c) a test-side deadline bug fixed locally** and away from **(a) report upstream to zdtp**. It does not decide it for you — capture the actual signature as chartered. But if the captured signature is a deadline expiry rather than `document.getElementById is not a function`, #3465 is the same root cause and both should be fixed together by one config-level change.

Note the two suites hit the same trap through different doors: eject-logo via an untimed `spawnSync`, design-token-panel-bootstrap via 39 bare `vi.waitFor()` calls (vitest 4.1.0 default timeout: 1000 ms). Both are `/test-wisdom`'s "two independent deadlines".

**Comment by Takazudo** [comment]
### flake-diagnosis — completed

**Outcome (d): the DTP file's failure did not reproduce — 0/16 full runs, 0/3 scoped max-starvation runs; the campaign instead captured the package-level deadline problem live in four other suites.**

- Budget: 16/20 full runs, 21/45 min (stopped early — signal saturated). 13/14 contended runs failed, never in `design-token-panel-bootstrap.test.ts`.
- Every captured failure is a vitest deadline expiry (`Error: Test timed out in 5000ms.` / one `Hook timed out in 60000ms.`) in `resolution-chain`, `eject-logo/cli-smoke` (#3465's mechanism, live), `highlight-runtime.integration`, `theme-packs-tarball`. Zero `getElementById`, zero unhandled rejections — outcome (a) has no supporting evidence.
- Rule 1 input diff (for the suites that failed): identical inputs, only load varied; recorded durations show slow completion, not misbehavior → test-side deadlines. For the DTP file no failing run exists; the #3429 cause remains open, plainly stated.
- Full findings: https://github.com/zudolab/zudo-doc/issues/3452#issuecomment-5329289473
- #3454 retitled to "Add deadline headroom + failure-diagnostics capture" and respecified with the concrete outcome-(d) spec (marker block preserved).
- No production code, no quarantine, branch intentionally empty; durable note at `cclogs/zudo-doc/flake-diagnosis-3453/findings.md`.

**Comment by Takazudo** [comment]
Closing — completed and merged via epic-PR #3467 (see completion comment above).
