### ISSUE TITLE
[DTP Bootstrap Flake][Epic] Diagnose the design-token-panel-bootstrap flake recurrence before fixing it

### ISSUE THREAD

**Issue by Takazudo** [zudolab/zudo-doc#3452]
This is an epic tracking issue for the **DTP Bootstrap Flake** implementation.

Supersedes: #3439

**Super-epic:** #3443
**Super-epic base branch:** `base/sweep-260818`
**This epic's base branch:** `base/sweep-260818-dtp-bootstrap-flake`

**Parent branch:** `base/sweep-260818`

Implementation will be done via `/x-wt-teams` — child branches merge into this epic's base branch, which then merges into `base/sweep-260818` as one PR.

## Overview

`packages/zudo-doc/src/__tests__/design-token-panel-bootstrap.test.ts` failed once under CPU contention during epic #3429 wave 2, in a package that sub-issue does not touch. It passed in isolation and on a clean full-suite re-run.

This matters because #3344 tracked **this exact test flaking under parallel load** and was closed on 2026-08-10 by bumping `@takazudo/zdtp` 0.4.9 → 0.4.10 (PR #3355), adopting upstream fix `Takazudo/zudo-design-token-panel#568`. This repo is on the fixed version (root pin `0.4.10`, package peer floor `^0.4.10`). So the symptom that fix was meant to eliminate has recurred on the fixed version.

#3355's own session report carried the caveat that one green parallel run is weak evidence for a flake fix. That caveat now looks load-bearing.

## The gap this epic closes first

**The error signature was never captured.** Without it, this is a recurrence of a *symptom*, not a confirmed recurrence of the *cause* #3344 described (`document.getElementById is not a function`, an unhandled rejection from bundled zdtp). It may be that same race surviving 0.4.10, a second distinct race, or an unrelated contention failure that happens to hit the same file.

So Wave 1 is diagnosis, not repair — per `/test-wisdom` Rule 1, *"flaky is not a diagnosis; it is an admission you have not diagnosed it yet."* Wave 2 implements whatever the diagnosis selects.

## A concrete hypothesis worth checking first

Found while planning, and cheap to test:

- `packages/zudo-doc/vitest.config.ts` sets **no `testTimeout`**, so tests run on vitest's 5000 ms default.
- The test file makes **39 bare `vi.waitFor()` calls** with no explicit timeout.
- The installed vitest **4.1.0** typings document `waitFor`'s defaults as `timeout` **1000 ms**, `interval` 50 ms (read from `dist/index.d.ts` — verified, not assumed).

That is `/test-wisdom`'s "two independent deadlines" shape: under contention the tighter 1000 ms deadline fires first and the failure reads as a flake while having nothing to do with zdtp. Confirming or refuting this changes the outcome completely — a local test fix versus an upstream report.

## Explicitly not doing

**No quarantine before a diagnosis.** Quarantining hides exactly the signal Wave 1 exists to capture. `/test-wisdom` gates quarantine behind a proven test-not-product finding, and #3439 says the same.

## Wave plan

- Wave 1: #3453
- Wave 2: #3454

## Sub-issues

| # | Wave | Task |
| --- | --- | --- |
| #3453 | 1 | Reproduce within a fixed budget, capture the signature, choose the direction |
| #3454 | 2 | Apply the remedy the diagnosis selected |

Close each sub-issue as its implementation is merged.

**Comment by Takazudo** [comment]
🤖 Starting work on this epic in a Claude Code session (`/x-wt-teams` Super-Epic child). To avoid conflicts, please check the latest comments before starting another session on this epic.

**Comment by Takazudo** [comment]
## Wave 1 diagnosis (#3453): outcome (d) — the DTP file's failure did not reproduce in 16 runs; the campaign instead caught the package-level deadline problem live in four *other* suites

### Budget spent: 16/20 full runs, 21/45 minutes — stopped early because the signal saturated

16 full runs of `pnpm --filter @takazudo/zudo-doc test` (2224 tests / 192 files) at `eb9032140`: 2 idle (both green) + 14 under deliberate CPU contention (24 → 240 busy-loop hogs on 12 CPUs). Plus 3 scoped runs of the DTP file alone under 240 hogs.

### Failure rate: 13/14 contended runs failed — 0/16 in `design-token-panel-bootstrap.test.ts`

The chartered file **never failed**, not even scoped-and-starved at 20x CPU oversubscription. Every failure that did occur is a vitest **deadline expiry**, verbatim:

```
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
```

| Suite | Mechanism | Failed in |
| --- | --- | --- |
| `src/__tests__/resolution-chain.test.ts` | real `tsc` type-check, 11.3-18.4 s under load vs 5000 ms default | 13/14 contended runs |
| `src/eject-logo/__tests__/cli-smoke.test.ts` | untimed `spawnSync` — **#3465's exact mechanism, reproduced live** (5479 ms) | 3 runs (120+ hogs) |
| `src/html-preview-wrapper/__tests__/highlight-runtime.integration.test.ts` | real WASM load (5056 ms) | 3 runs (120+ hogs) |
| `src/__tests__/theme-packs-tarball.test.ts` | `npm pack` in a hook — `Error: Hook timed out in 60000ms.` | 1 run (240 hogs) |

Grep across all 19 logs: **zero** `document.getElementById`, **zero** unhandled rejections, **zero** non-timeout errors. Outcome (a) — a surviving zdtp race — has no supporting evidence anywhere in the campaign.

### Rule 1 input diff: test-side deadline, not product bug — for the suites that failed

Identical commit, command, fixtures, and env between passing and failing runs; the only variable was load. The failing tests' recorded durations show the product operations *completing slowly, not misbehaving* (tsc finishes at 11-18 s; the CLI subprocess completes at 5.4 s). For the DTP file itself no failing run exists, so no diff is possible — its one historical failure (#3429 wave 2) remains signature-less, and outcome (c) is **not** claimed for it.

### Why the DTP file resists starvation

Scoped probe (file alone + 240 hogs): 3/3 green, slowest individual test **235 ms** against the 1000 ms bare-`vi.waitFor` deadline. Its waits are in-process microtasks over a mocked zdtp — no subprocess, no tsc, no WASM, no disk. The epic's hypothesis facts all verified (no `testTimeout` in `packages/zudo-doc/vitest.config.ts`; 39 bare `vi.waitFor()` calls with zero explicit timeouts; vitest 4.1.0 defaults 1000 ms / 50 ms) — a genuine headroom liability, but with ~4x margin under far-beyond-realistic load.

### Decision: (d) — no invented fix; Wave 2 = deadline headroom + failure-diagnostics capture

The #3429 incident's cause stays open, plainly stated. #3454 is retitled and respecified accordingly: config-level `testTimeout`/`hookTimeout` headroom plus an explicit `vi.waitFor` timeout constant (diagnosable expiry margins, per /test-wisdom's "align the two deadlines at config level, not per-test"), and diagnostics so any future DTP failure captures its signature. This remedy is simultaneously **evidence-backed** for the four suites that did fail — the #3465 family, same root cause, fixed together.

Durable record: `cclogs/zudo-doc/flake-diagnosis-3453/findings.md`. No production code changed, no quarantine applied, branch intentionally empty.

**Comment by Takazudo** [comment]
Epic-PR merged into `base/sweep-260818`: https://github.com/zudolab/zudo-doc/pull/3467
